version: '3.9'

services:
  db:
    image: postgres:16
    container_name: cms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms_web
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn cms_project.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    environment:
      DB_NAME: test
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: localhost
      DB_PORT: 5432
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: cms_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
