# Generated by Django 4.2.4 on 2023-08-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='blog_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='user_id',
        ),
    ]
